# Na raiz do projeto: Muni-moldes-website/docker-compose.yml
version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: muni_moldes_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: catalogo_db
    ports:
      - "5432:5432"
    volumes:
      # Para persistir os dados do banco fora do container
      - ./pgdata:/var/lib/postgresql/data